// ==================== COMPRESSED LOCATION DATA ====================
// Format: [code, name] for countries, states[code] = [state names]
// Uses ISO 3166-1 alpha-2 codes for compression

const locationData = (function() {

// All countries as [ISO code, name] pairs
var countries = [
["AF","Afghanistan"],["AL","Albania"],["DZ","Algeria"],["AD","Andorra"],["AO","Angola"],
["AG","Antigua & Barbuda"],["AR","Argentina"],["AM","Armenia"],["AU","Australia"],
["AT","Austria"],["AZ","Azerbaijan"],["BS","Bahamas"],["BH","Bahrain"],["BD","Bangladesh"],
["BB","Barbados"],["BY","Belarus"],["BE","Belgium"],["BZ","Belize"],["BJ","Benin"],
["BT","Bhutan"],["BO","Bolivia"],["BA","Bosnia & Herzegovina"],["BW","Botswana"],
["BR","Brazil"],["BN","Brunei"],["BG","Bulgaria"],["BF","Burkina Faso"],["BI","Burundi"],
["KH","Cambodia"],["CM","Cameroon"],["CA","Canada"],["CV","Cape Verde"],
["CF","Central African Republic"],["TD","Chad"],["CL","Chile"],["CN","China"],
["CO","Colombia"],["KM","Comoros"],["CG","Congo"],["CD","Congo (DRC)"],
["CR","Costa Rica"],["CI","Côte d'Ivoire"],["HR","Croatia"],["CU","Cuba"],
["CY","Cyprus"],["CZ","Czech Republic"],["DK","Denmark"],["DJ","Djibouti"],
["DM","Dominica"],["DO","Dominican Republic"],["TL","East Timor"],
["EC","Ecuador"],["EG","Egypt"],["SV","El Salvador"],["GQ","Equatorial Guinea"],
["ER","Eritrea"],["EE","Estonia"],["SZ","Eswatini"],["ET","Ethiopia"],
["FJ","Fiji"],["FI","Finland"],["FR","France"],["GA","Gabon"],["GM","Gambia"],
["GE","Georgia"],["DE","Germany"],["GH","Ghana"],["GR","Greece"],["GD","Grenada"],
["GT","Guatemala"],["GN","Guinea"],["GW","Guinea-Bissau"],["GY","Guyana"],
["HT","Haiti"],["HN","Honduras"],["HU","Hungary"],["IS","Iceland"],
["IN","India"],["ID","Indonesia"],["IR","Iran"],["IQ","Iraq"],["IE","Ireland"],
["IL","Israel"],["IT","Italy"],["JM","Jamaica"],["JP","Japan"],["JO","Jordan"],
["KZ","Kazakhstan"],["KE","Kenya"],["KI","Kiribati"],["KP","North Korea"],
["KR","South Korea"],["XK","Kosovo"],["KW","Kuwait"],["KG","Kyrgyzstan"],
["LA","Laos"],["LV","Latvia"],["LB","Lebanon"],["LS","Lesotho"],["LR","Liberia"],
["LY","Libya"],["LI","Liechtenstein"],["LT","Lithuania"],["LU","Luxembourg"],
["MG","Madagascar"],["MW","Malawi"],["MY","Malaysia"],["MV","Maldives"],
["ML","Mali"],["MT","Malta"],["MH","Marshall Islands"],["MR","Mauritania"],
["MU","Mauritius"],["MX","Mexico"],["FM","Micronesia"],["MD","Moldova"],
["MC","Monaco"],["MN","Mongolia"],["ME","Montenegro"],["MA","Morocco"],
["MZ","Mozambique"],["MM","Myanmar"],["NA","Namibia"],["NR","Nauru"],
["NP","Nepal"],["NL","Netherlands"],["NZ","New Zealand"],["NI","Nicaragua"],
["NE","Niger"],["NG","Nigeria"],["MK","North Macedonia"],["NO","Norway"],
["OM","Oman"],["PK","Pakistan"],["PW","Palau"],["PS","Palestine"],
["PA","Panama"],["PG","Papua New Guinea"],["PY","Paraguay"],["PE","Peru"],
["PH","Philippines"],["PL","Poland"],["PT","Portugal"],["QA","Qatar"],
["RO","Romania"],["RU","Russia"],["RW","Rwanda"],["KN","St Kitts & Nevis"],
["LC","St Lucia"],["VC","St Vincent"],["WS","Samoa"],["SM","San Marino"],
["ST","Sao Tome & Principe"],["SA","Saudi Arabia"],["SN","Senegal"],
["RS","Serbia"],["SC","Seychelles"],["SL","Sierra Leone"],["SG","Singapore"],
["SK","Slovakia"],["SI","Slovenia"],["SB","Solomon Islands"],["SO","Somalia"],
["ZA","South Africa"],["SS","South Sudan"],["ES","Spain"],["LK","Sri Lanka"],
["SD","Sudan"],["SR","Suriname"],["SE","Sweden"],["CH","Switzerland"],
["SY","Syria"],["TW","Taiwan"],["TJ","Tajikistan"],["TZ","Tanzania"],
["TH","Thailand"],["TG","Togo"],["TO","Tonga"],["TT","Trinidad & Tobago"],
["TN","Tunisia"],["TR","Turkey"],["TM","Turkmenistan"],["TV","Tuvalu"],
["UG","Uganda"],["UA","Ukraine"],["AE","United Arab Emirates"],
["GB","United Kingdom"],["US","United States"],["UY","Uruguay"],
["UZ","Uzbekistan"],["VU","Vanuatu"],["VA","Vatican City"],
["VE","Venezuela"],["VN","Vietnam"],["YE","Yemen"],["ZM","Zambia"],
["ZW","Zimbabwe"],
// Territories & Dependencies
["AX","Åland Islands"],["AI","Anguilla"],["AW","Aruba"],["BM","Bermuda"],
["BQ","Bonaire"],["IO","British Indian Ocean Territory"],["VG","British Virgin Islands"],
["KY","Cayman Islands"],["CX","Christmas Island"],["CC","Cocos Islands"],
["CK","Cook Islands"],["CW","Curaçao"],["FK","Falkland Islands"],
["FO","Faroe Islands"],["GF","French Guiana"],["PF","French Polynesia"],
["GI","Gibraltar"],["GL","Greenland"],["GP","Guadeloupe"],["GU","Guam"],
["GG","Guernsey"],["HK","Hong Kong"],["JE","Jersey"],["MO","Macau"],
["MQ","Martinique"],["YT","Mayotte"],["MS","Montserrat"],["NC","New Caledonia"],
["NU","Niue"],["NF","Norfolk Island"],["MP","Northern Mariana Islands"],
["RE","Réunion"],["BL","St Barthélemy"],["MF","St Martin"],
["PM","St Pierre & Miquelon"],["SX","Sint Maarten"],["GS","South Georgia"],
["SJ","Svalbard"],["TK","Tokelau"],["TC","Turks & Caicos Islands"],
["VI","US Virgin Islands"],["WF","Wallis & Futuna"],["EH","Western Sahara"]
];

// States, provinces, prefectures for countries that have them
var states = {
  ZA: ["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","North West","Northern Cape","Western Cape"],
  US: ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming","District of Columbia"],
  CA: ["Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland & Labrador","Nova Scotia","Ontario","Prince Edward Island","Quebec","Saskatchewan","Northwest Territories","Nunavut","Yukon"],
  GB: ["England","Scotland","Wales","Northern Ireland"],
  AU: ["New South Wales","Victoria","Queensland","Western Australia","South Australia","Tasmania","Australian Capital Territory","Northern Territory"],
  DE: ["Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"],
  FR: ["Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Brittany","Centre-Val de Loire","Corsica","Grand Est","Hauts-de-France","Île-de-France","Normandy","Nouvelle-Aquitaine","Occitanie","Pays de la Loire","Provence-Alpes-Côte d'Azur"],
  ES: ["Andalusia","Aragon","Asturias","Balearic Islands","Basque Country","Canary Islands","Cantabria","Castile and León","Castilla-La Mancha","Catalonia","Extremadura","Galicia","La Rioja","Madrid","Murcia","Navarre","Valencia"],
  IT: ["Abruzzo","Aosta Valley","Apulia","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli-Venezia Giulia","Lazio","Liguria","Lombardy","Marche","Molise","Piedmont","Sardinia","Sicily","Tuscany","Trentino-South Tyrol","Umbria","Veneto"],
  JP: ["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"],
  BR: ["Acre","Alagoas","Amapá","Amazonas","Bahia","Ceará","Distrito Federal","Espírito Santo","Goiás","Maranhão","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Pará","Paraíba","Paraná","Pernambuco","Piauí","Rio de Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondônia","Roraima","Santa Catarina","São Paulo","Sergipe","Tocantins"],
  IN: ["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Andaman & Nicobar","Chandigarh","Dadra & Nagar Haveli","Daman & Diu","Delhi","Jammu & Kashmir","Ladakh","Lakshadweep","Puducherry"],
  CN: ["Anhui","Beijing","Chongqing","Fujian","Gansu","Guangdong","Guangxi","Guizhou","Hainan","Hebei","Heilongjiang","Henan","Hubei","Hunan","Inner Mongolia","Jiangsu","Jiangxi","Jilin","Liaoning","Ningxia","Qinghai","Shaanxi","Shandong","Shanghai","Shanxi","Sichuan","Tianjin","Tibet","Xinjiang","Yunnan","Zhejiang","Hong Kong","Macau"],
  RU: ["Altai Krai","Amur","Arkhangelsk","Astrakhan","Belgorod","Bryansk","Chelyabinsk","Irkutsk","Ivanovo","Kaliningrad","Kaluga","Kemerovo","Khabarovsk","Krasnodar","Krasnoyarsk","Kurgan","Kursk","Leningrad","Lipetsk","Magadan","Moscow","Moscow City","Murmansk","Nizhny Novgorod","Novgorod","Novosibirsk","Omsk","Orenburg","Oryol","Penza","Perm","Primorsky","Pskov","Rostov","Ryazan","Saint Petersburg","Sakha","Sakhalin","Samara","Saratov","Smolensk","Stavropol","Sverdlovsk","Tambov","Tatarstan","Tomsk","Tula","Tver","Tyumen","Ulyanovsk","Vladimir","Volgograd","Vologda","Voronezh","Yaroslavl"],
  MX: ["Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Coahuila","Colima","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","Mexico City","México","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"],
  NG: ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"],
  AR: ["Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucumán"],
  ID: ["Aceh","Bali","Banten","Bengkulu","Central Java","Central Kalimantan","Central Sulawesi","East Java","East Kalimantan","East Nusa Tenggara","Gorontalo","Jakarta","Jambi","Lampung","Maluku","North Kalimantan","North Maluku","North Sulawesi","North Sumatra","Papua","Riau","Riau Islands","South Kalimantan","South Sulawesi","South Sumatra","Southeast Sulawesi","West Java","West Kalimantan","West Nusa Tenggara","West Papua","West Sulawesi","West Sumatra","Yogyakarta"],
  TR: ["Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkâri","Hatay","Iğdır","Isparta","Istanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kırıkkale","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Şanlıurfa","Siirt","Sinop","Sivas","Şırnak","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"],
  KR: ["Busan","Chungbuk","Chungnam","Daegu","Daejeon","Gangwon","Gwangju","Gyeongbuk","Gyeonggi","Gyeongnam","Incheon","Jeju","Jeonbuk","Jeonnam","Sejong","Seoul","Ulsan"],
  KE: ["Baringo","Bomet","Bungoma","Busia","Elgeyo-Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang'a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita-Taveta","Tana River","Tharaka-Nithi","Trans-Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"],
  TZ: ["Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Kaskazini Pemba","Kaskazini Unguja","Katavi","Kigoma","Kilimanjaro","Kusini Pemba","Kusini Unguja","Lindi","Manyara","Mara","Mbeya","Mjini Magharibi","Morogoro","Mtwara","Mwanza","Njombe","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga"],
  EG: ["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Ismailia","Kafr el-Sheikh","Luxor","Matrouh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"],
  PH: ["Abra","Agusan del Norte","Agusan del Sur","Aklan","Albay","Antique","Apayao","Aurora","Basilan","Bataan","Batanes","Batangas","Benguet","Biliran","Bohol","Bukidnon","Bulacan","Cagayan","Camarines Norte","Camarines Sur","Camiguin","Capiz","Catanduanes","Cavite","Cebu","Cotabato","Davao de Oro","Davao del Norte","Davao del Sur","Davao Occidental","Davao Oriental","Dinagat Islands","Eastern Samar","Guimaras","Ifugao","Ilocos Norte","Ilocos Sur","Iloilo","Isabela","Kalinga","La Union","Laguna","Lanao del Norte","Lanao del Sur","Leyte","Maguindanao","Marinduque","Masbate","Metro Manila","Misamis Occidental","Misamis Oriental","Mountain Province","Negros Occidental","Negros Oriental","Northern Samar","Nueva Ecija","Nueva Vizcaya","Occidental Mindoro","Oriental Mindoro","Palawan","Pampanga","Pangasinan","Quezon","Quirino","Rizal","Romblon","Samar","Sarangani","Siquijor","Sorsogon","South Cotabato","Southern Leyte","Sultan Kudarat","Sulu","Surigao del Norte","Surigao del Sur","Tarlac","Tawi-Tawi","Zambales","Zamboanga del Norte","Zamboanga del Sur","Zamboanga Sibugay"],
  VN: ["An Giang","Bà Rịa-Vũng Tàu","Bắc Giang","Bắc Kạn","Bạc Liêu","Bắc Ninh","Bến Tre","Bình Dương","Bình Định","Bình Phước","Bình Thuận","Cà Mau","Cần Thơ","Cao Bằng","Đà Nẵng","Đắk Lắk","Đắk Nông","Điện Biên","Đồng Nai","Đồng Tháp","Gia Lai","Hà Giang","Hà Nam","Hà Nội","Hà Tĩnh","Hải Dương","Hải Phòng","Hậu Giang","Hòa Bình","Hồ Chí Minh City","Hưng Yên","Khánh Hòa","Kiên Giang","Kon Tum","Lai Châu","Lâm Đồng","Lạng Sơn","Lào Cai","Long An","Nam Định","Nghệ An","Ninh Bình","Ninh Thuận","Phú Thọ","Phú Yên","Quảng Bình","Quảng Nam","Quảng Ngãi","Quảng Ninh","Quảng Trị","Sóc Trăng","Sơn La","Tây Ninh","Thái Bình","Thái Nguyên","Thanh Hóa","Thừa Thiên-Huế","Tiền Giang","Trà Vinh","Tuyên Quang","Vĩnh Long","Vĩnh Phúc","Yên Bái"],
  TH: ["Amnat Charoen","Ang Thong","Bangkok","Bueng Kan","Buri Ram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chon Buri","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Lampang","Lamphun","Loei","Lop Buri","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lam Phu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phang Nga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phra Nakhon Si Ayutthaya","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Saraburi","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon"],
  NG: ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"],
  PK: ["Azad Kashmir","Balochistan","Gilgit-Baltistan","Islamabad","Khyber Pakhtunkhwa","Punjab","Sindh"],
  BD: ["Barisal","Chittagong","Dhaka","Khulna","Mymensingh","Rajshahi","Rangpur","Sylhet"],
  ZW: ["Bulawayo","Harare","Manicaland","Mashonaland Central","Mashonaland East","Mashonaland West","Masvingo","Matabeleland North","Matabeleland South","Midlands"],
  ZM: ["Central","Copperbelt","Eastern","Luapula","Lusaka","Muchinga","Northern","North-Western","Southern","Western"],
  MW: ["Central Region","Northern Region","Southern Region"],
  MZ: ["Cabo Delgado","Gaza","Inhambane","Manica","Maputo","Nampula","Niassa","Sofala","Tete","Zambezia"],
  AO: ["Bengo","Benguela","Bié","Cabinda","Cuando Cubango","Cuanza Norte","Cuanza Sul","Cunene","Huambo","Huíla","Luanda","Lunda Norte","Lunda Sul","Malanje","Moxico","Namibe","Uíge","Zaire"],
  NA: ["Erongo","Hardap","Karas","Kavango East","Kavango West","Khomas","Kunene","Ohangwena","Omaheke","Omusati","Oshana","Oshikoto","Otjozondjupa","Zambezi"],
  BW: ["Central","Chobe","Francistown","Gaborone","Ghanzi","Jwaneng","Kgalagadi","Kgatleng","Kweneng","Lobatse","Molepolole","Ngamiland","North-East","Selibe Phikwe","South-East","Southern","Sowa"],
  LS: ["Berea","Butha-Buthe","Leribe","Mafeteng","Maseru","Mohale's Hoek","Mokhotlong","Qacha's Nek","Quthing","Thaba-Tseka"],
  SZ: ["Hhohho","Lubombo","Manzini","Shiselweni"],
  GH: ["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"],
  ET: ["Addis Ababa","Afar","Amhara","Benishangul-Gumuz","Dire Dawa","Gambela","Harari","Oromia","Sidama","Somali","Southern Nations","Tigray"],
  UG: ["Central","Eastern","Northern","Western"],
  CM: ["Adamawa","Centre","East","Far North","Littoral","North","Northwest","South","Southwest","West"],
  CI: ["Abidjan","Bas-Sassandra","Comoé","Denguélé","Gôh-Djiboua","Lacs","Lagunes","Montagnes","Sassandra-Marahoué","Savanes","Vallée du Bandama","Woroba","Yamoussoukro","Zanzan"],
  SN: ["Dakar","Diourbel","Fatick","Kaffrine","Kaolack","Kédougou","Kolda","Louga","Matam","Saint-Louis","Sédhiou","Tambacounda","Thiès","Ziguinchor"],
  MA: ["Béni Mellal-Khénifra","Casablanca-Settat","Dakhla-Oued Ed-Dahab","Drâa-Tafilalet","Fès-Meknès","Guelmim-Oued Noun","Laâyoune-Sakia El Hamra","Marrakech-Safi","Monaco","Oriental","Rabat-Salé-Kénitra","Souss-Massa","Tanger-Tétouan-Al Hoceïma"],
  DZ: ["Adrar","Aïn Defla","Aïn Témouchent","Algiers","Annaba","Batna","Béchar","Béjaïa","Biskra","Blida","Bordj Bou Arréridj","Bouira","Boumerdès","Chlef","Constantine","Djelfa","El Bayadh","El Oued","El Tarf","Ghardaïa","Guelma","Illizi","Jijel","Khenchela","Laghouat","Mascara","Médéa","Mila","Mostaganem","Msila","Naâma","Oran","Ouargla","Oum El Bouaghi","Relizane","Saïda","Sétif","Sidi Bel Abbès","Skikda","Souk Ahras","Tamanrasset","Tébessa","Tiaret","Tindouf","Tipaza","Tissemsilt","Tizi Ouzou","Tlemcen"],
  TN: ["Ariana","Béja","Ben Arous","Bizerte","Gabès","Gafsa","Jendouba","Kairouan","Kasserine","Kébili","Kef","Mahdia","Manouba","Médenine","Monastir","Nabeul","Sfax","Sidi Bouzid","Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan"],
  LY: ["Al Wahat","Benghazi","Derna","Ghat","Jabal al Akhdar","Jabal al Gharbi","Jafara","Jufra","Kufra","Marqab","Misrata","Murqub","Murzuq","Nalut","Nuqat al Khams","Sabha","Sirte","Tripoli","Wadi al Hayaa","Wadi al Shatii","Zawiya"],
  SD: ["Al Jazirah","Al Qadarif","Blue Nile","Central Darfur","East Darfur","Kassala","Khartoum","North Darfur","North Kordofan","Northern","Red Sea","River Nile","Sennar","South Darfur","South Kordofan","West Darfur","West Kordofan","White Nile"],
  EG: ["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Ismailia","Kafr el-Sheikh","Luxor","Matrouh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"],
  SE: ["Blekinge","Dalarna","Gävleborg","Gotland","Halland","Jämtland","Jönköping","Kalmar","Kronoberg","Norrbotten","Örebro","Östergötland","Skåne","Södermanland","Stockholm","Uppsala","Värmland","Västerbotten","Västernorrland","Västmanland","Västra Götaland"],
  NO: ["Agder","Innlandet","Møre og Romsdal","Nordland","Oslo","Rogaland","Troms og Finnmark","Trøndelag","Vestfold og Telemark","Vestland","Viken"],
  FI: ["Åland","Central Finland","Central Ostrobothnia","Finland Proper","Kainuu","Kymenlaakso","Lapland","North Karelia","North Ostrobothnia","North Savo","Ostrobothnia","Päijät-Häme","Pirkanmaa","Satakunta","South Karelia","South Ostrobothnia","South Savo","Uusimaa"],
  DK: ["Capital Region","Central Jutland","North Jutland","Region Zealand","South Denmark"],
  PL: ["Greater Poland","Kuyavia-Pomerania","Lesser Poland","Lower Silesia","Lublin","Lubusz","Łódź","Masovia","Opole","Podlaskie","Pomerania","Silesia","Subcarpathia","Świętokrzyskie","Warmia-Masuria","West Pomerania"],
  CZ: ["Central Bohemia","Hradec Králové","Karlovy Vary","Liberec","Moravia-Silesia","Olomouc","Pardubice","Plzeň","Prague","South Bohemia","South Moravia","Ústí nad Labem","Vysočina","Zlín"],
  SK: ["Banská Bystrica","Bratislava","Košice","Nitra","Prešov","Trenčín","Trnava","Žilina"],
  HU: ["Bács-Kiskun","Baranya","Békés","Borsod-Abaúj-Zemplén","Budapest","Csongrád","Fejér","Győr-Moson-Sopron","Hajdú-Bihar","Heves","Jász-Nagykun-Szolnok","Komárom-Esztergom","Nógrád","Pest","Somogy","Szabolcs-Szatmár-Bereg","Tolna","Vas","Veszprém","Zala"],
  RO: ["Alba","Arad","Argeș","Bacău","Bihor","Bistrița-Năsăud","Botoșani","Brașov","Brăila","Bucharest","Buzău","Călărași","Caraș-Severin","Cluj","Constanța","Covasna","Dâmbovița","Dolj","Galați","Giurgiu","Gorj","Harghita","Hunedoara","Ialomița","Iași","Ilfov","Maramureș","Mehedinți","Mureș","Neamț","Olt","Prahova","Satu Mare","Sălaj","Sibiu","Suceava","Teleorman","Timiș","Tulcea","Vâlcea","Vaslui","Vrancea"],
  GR: ["Attica","Central Greece","Central Macedonia","Crete","Eastern Macedonia & Thrace","Epirus","Ionian Islands","North Aegean","Peloponnese","South Aegean","Thessaly","Western Greece","Western Macedonia"],
  BG: ["Blagoevgrad","Burgas","Dobrich","Gabrovo","Haskovo","Kardzhali","Kyustendil","Lovech","Montana","Pazardzhik","Pernik","Pleven","Plovdiv","Razgrad","Ruse","Shumen","Silistra","Sliven","Smolyan","Sofia","Sofia City","Stara Zagora","Targovishte","Varna","Veliko Tarnovo","Vidin","Vratsa","Yambol"],
  PT: ["Aveiro","Azores","Beja","Braga","Bragança","Castelo Branco","Coimbra","Évora","Faro","Guarda","Leiria","Lisbon","Madeira","Portalegre","Porto","Santarém","Setúbal","Viana do Castelo","Vila Real","Viseu"],
  BE: ["Antwerp","Brussels","East Flanders","Flemish Brabant","Hainaut","Liège","Limburg","Luxembourg","Namur","Walloon Brabant","West Flanders"],
  NL: ["Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg","North Brabant","North Holland","Overijssel","South Holland","Utrecht","Zeeland"],
  CH: ["Aargau","Appenzell Ausserrhoden","Appenzell Innerrhoden","Basel-Landschaft","Basel-Stadt","Bern","Fribourg","Geneva","Glarus","Graubünden","Jura","Lucerne","Neuchâtel","Nidwalden","Obwalden","Schaffhausen","Schwyz","Solothurn","St. Gallen","Thurgau","Ticino","Uri","Valais","Vaud","Zug","Zürich"],
  AT: ["Burgenland","Carinthia","Lower Austria","Salzburg","Styria","Tyrol","Upper Austria","Vienna","Vorarlberg"],
  IE: ["Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway","Kerry","Kildare","Kilkenny","Laois","Leitrim","Limerick","Longford","Louth","Mayo","Meath","Monaghan","Offaly","Roscommon","Sligo","Tipperary","Waterford","Westmeath","Wexford","Wicklow"],
  HR: ["Bjelovar-Bilogora","Brod-Posavina","Dubrovnik-Neretva","Istria","Karlovac","Koprivnica-Križevci","Krapina-Zagorje","Lika-Senj","Međimurje","Osijek-Baranja","Požega-Slavonia","Primorje-Gorski Kotar","Šibenik-Knin","Slavonski Brod-Posavina","Split-Dalmatia","Varaždin","Virovitica-Podravina","Vukovar-Srijem","Zadar","Zagreb","Zagreb City"],
  SI: ["Gorenjska","Goriška","Jugovzhodna Slovenija","Koroška","Obalno-kraška","Osrednjeslovenska","Podravska","Pomurska","Posavska","Primorsko-notranjska","Savinjska","Zasavska"],
  MY: ["Johor","Kedah","Kelantan","Kuala Lumpur","Labuan","Malacca","Negeri Sembilan","Pahang","Penang","Perak","Perlis","Putrajaya","Sabah","Sarawak","Selangor","Terengganu"],
  SG: [],
  AE: ["Abu Dhabi","Ajman","Dubai","Fujairah","Ras Al Khaimah","Sharjah","Umm Al Quwain"],
  IQ: ["Al Anbar","Al Muthanna","Al-Qadisiyyah","Babylon","Baghdad","Basra","Dhi Qar","Diyala","Dohuk","Erbil","Halabja","Karbala","Kirkuk","Maysan","Najaf","Nineveh","Saladin","Sulaymaniyah","Wasit"],
  SA: ["Al Bahah","Al Jawf","Al Madinah","Al Qassim","Asir","Eastern Province","Ha'il","Jazan","Makkah","Najran","Northern Borders","Riyadh","Tabuk"],
  YE: ["Abyan","Aden","Al Bayda","Al Hudaydah","Al Jawf","Al Mahrah","Al Mahwit","Amran","Dhamar","Hadramaut","Hajjah","Ibb","Lahij","Ma'rib","Raymah","Saada","Sana'a","Sana'a City","Shabwah","Socotra","Taiz"],
  OM: ["Ad Dakhiliyah","Ad Dhahirah","Al Batinah North","Al Batinah South","Al Buraimi","Al Wusta","Ash Sharqiyah North","Ash Sharqiyah South","Dhofar","Musandam","Muscat"],
  KW: ["Ahmadi","Farwaniya","Hawalli","Jahra","Mubarak Al-Kabeer"],
  QA: ["Al Daayen","Al Khor","Al Rayyan","Al Shamal","Al Wakrah","Al-Shahaniya","Doha","Umm Salal"],
  BH: ["Capital","Central","Muharraq","Northern","Southern"],
  JO: ["Ajloun","Amman","Aqaba","Balqa","Irbid","Jarash","Karak","Ma'an","Madaba","Mafraq","Tafilah","Zarqa"],
  LB: ["Akkar","Baalbek-Hermel","Beirut","Beqaa","Mount Lebanon","Nabatieh","North","South"],
  SY: ["Aleppo","Damascus","Daraa","Deir ez-Zor","Hama","Al-Hasakah","Homs","Idlib","Latakia","Quneitra","Raqqa","Rif Dimashq","Sweida","Tartus"],
  IL: ["Central","Haifa","Jerusalem","Northern","South","Tel Aviv"],
  PT: ["Aveiro","Azores","Beja","Braga","Bragança","Castelo Branco","Coimbra","Évora","Faro","Guarda","Leiria","Lisbon","Madeira","Portalegre","Porto","Santarém","Setúbal","Viana do Castelo","Vila Real","Viseu"],
  PE: ["Amazonas","Áncash","Apurímac","Arequipa","Ayacucho","Cajamarca","Callao","Cusco","Huancavelica","Huánuco","Ica","Junín","La Libertad","Lambayeque","Lima","Loreto","Madre de Dios","Moquegua","Pasco","Piura","Puno","San Martín","Tacna","Tumbes","Ucayali"],
  CO: ["Amazonas","Antioquia","Arauca","Atlántico","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"],
  CL: ["Antofagasta","Araucanía","Arica y Parinacota","Atacama","Aysén","Biobío","Coquimbo","Los Lagos","Los Ríos","Magallanes","Maule","Ñuble","O'Higgins","Santiago","Tarapacá","Valparaíso"],
  NZ: ["Auckland","Bay of Plenty","Canterbury","Chatham Islands","Gisborne","Hawke's Bay","Manawatu-Wanganui","Marlborough","Nelson","Northland","Otago","Southland","Taranaki","Tasman","Waikato","Wellington","West Coast"],
  CU: ["Artemisa","Camagüey","Ciego de Ávila","Cienfuegos","Granma","Guantánamo","Holguín","Isla de la Juventud","La Habana","Las Tunas","Matanzas","Mayabeque","Pinar del Río","Sancti Spíritus","Santiago de Cuba","Villa Clara"],
  DO: ["Azua","Baoruco","Barahona","Dajabón","Duarte","El Seibo","Elías Piña","Espaillat","Hato Mayor","Hermanas Mirabal","Independencia","La Altagracia","La Romana","La Vega","María Trinidad Sánchez","Monseñor Nouel","Monte Cristi","Monte Plata","Pedernales","Peravia","Puerto Plata","Samaná","San Cristóbal","San José de Ocoa","San Juan","San Pedro de Macorís","Sánchez Ramírez","Santiago","Santiago Rodríguez","Santo Domingo","Valverde"],
  PR: ["Adjuntas","Aguada","Aguadilla","Aguas Buenas","Aibonito","Arecibo","Arroyo","Barceloneta","Barranquitas","Bayamón","Cabo Rojo","Caguas","Camuy","Canóvanas","Carolina","Cataño","Cayey","Ceiba","Ciales","Cidra","Coamo","Comerío","Corozal","Culebra","Dorado","Fajardo","Florida","Guánica","Guayama","Guayanilla","Guaynabo","Gurabo","Hatillo","Hormigueros","Humacao","Isabela","Jayuya","Juana Díaz","Juncos","Lajas","Lares","Las Marías","Las Piedras","Loíza","Luquillo","Manatí","Maricao","Maunabo","Mayagüez","Moca","Morovis","Naguabo","Naranjito","Orocovis","Patillas","Peñuelas","Ponce","Quebradillas","Rincón","Río Grande","Sabana Grande","Salinas","San Germán","San Juan","San Lorenzo","San Sebastián","Santa Isabel","Toa Alta","Toa Baja","Trujillo Alto","Utuado","Vega Alta","Vega Baja","Vieques","Villalba","Yabucoa","Yauco"],
  PA: ["Bocas del Toro","Chiriquí","Coclé","Colón","Darién","Emberá","Herrera","Los Santos","Ngäbe-Buglé","Panamá","Panamá Oeste","Veraguas"],
  CR: ["Alajuela","Cartago","Guanacaste","Heredia","Limón","Puntarenas","San José"],
  NI: ["Boaco","Carazo","Chinandega","Chontales","Costa Caribe Norte","Costa Caribe Sur","Estelí","Granada","Jinotega","León","Madriz","Managua","Masaya","Matagalpa","Nueva Segovia","Río San Juan","Rivas"],
  GT: ["Alta Verapaz","Baja Verapaz","Chimaltenango","Chiquimula","El Progreso","Escuintla","Guatemala","Huehuetenango","Izabal","Jalapa","Jutiapa","Petén","Quetzaltenango","Quiché","Retalhuleu","Sacatepéquez","San Marcos","Santa Rosa","Sololá","Suchitepéquez","Totonicapán","Zacapa"],
  HN: ["Atlántida","Choluteca","Colón","Comayagua","Copán","Cortés","El Paraíso","Francisco Morazán","Gracias a Dios","Intibucá","Islas de la Bahía","La Paz","Lempira","Ocotepeque","Olancho","Santa Bárbara","Valle","Yoro"],
  SV: ["Ahuachapán","Cabañas","Chalatenango","Cuscatlán","La Libertad","La Paz","La Unión","Morazán","San Miguel","San Salvador","San Vicente","Santa Ana","Sonsonate","Usulután"],
  UY: ["Artigas","Canelones","Cerro Largo","Colonia","Durazno","Flores","Florida","Lavalleja","Maldonado","Montevideo","Paysandú","Río Negro","Rivera","Roca","Salto","San José","Soriano","Tacuarembó","Treinta y Tres"],
  PY: ["Alto Paraguay","Alto Paraná","Amambay","Asunción","Boquerón","Caaguazú","Caazapá","Canindeyú","Central","Concepción","Cordillera","Guairá","Itapúa","Misiones","Ñeembucú","Paraguarí","Presidente Hayes","San Pedro"],
  BO: ["Beni","Chuquisaca","Cochabamba","La Paz","Oruro","Pando","Potosí","Santa Cruz","Tarija"],
  VE: ["Amazonas","Anzoátegui","Apure","Aragua","Barinas","Bolívar","Carabobo","Cojedes","Delta Amacuro","Falcón","Guárico","La Guaira","Lara","Mérida","Miranda","Monagas","Nueva Esparta","Portuguesa","Sucre","Táchira","Trujillo","Yaracuy","Zulia"],
  EC: ["Azuay","Bolívar","Cañar","Carchi","Chimborazo","Cotopaxi","El Oro","Esmeraldas","Galápagos","Guayas","Imbabura","Loja","Los Ríos","Manabí","Morona Santiago","Napo","Orellana","Pastaza","Pichincha","Santa Elena","Santo Domingo","Sucumbíos","Tungurahua","Zamora Chinchipe"],
  // Carribean
  JM: ["Clarendon","Hanover","Kingston","Manchester","Portland","St Andrew","St Ann","St Catherine","St Elizabeth","St James","St Mary","St Thomas","Trelawny","Westmoreland"],
  TT: ["Arima","Chaguanas","Couva-Tabaquite","Diego Martin","Mayaro","Penal-Debe","Point Fortin","Port of Spain","Princes Town","San Fernando","San Juan-Laventille","Sangre Grande","Siparia","Tobago","Tunapuna-Piarco"],
  // Pacific
  FJ: ["Ba","Bua","Cakaudrove","Kadavu","Lau","Lomaiviti","Macuata","Nadroga-Navosa","Naitasiri","Namosi","Ra","Rewa","Rotuma","Serua","Tailevu"],
  SB: ["Central","Choiseul","Guadalcanal","Honiara","Isabel","Makira-Ulawa","Malaita","Rennell and Bellona","Temotu","Western"],
  VU: ["Malampa","Penama","Sanma","Shefa","Tafea","Torba"],
  WS: ["A'ana","Aiga-i-le-Tai","Atua","Fa'asaleleaga","Gaga'emauga","Gagaifomauga","Palauli","Satupa'itea","Tuamasaga","Va'a-o-Fonoti","Vaisigano"],
  TO: ["'Eua","Ha'apai","Niuas","Tongatapu","Vava'u"],
  // Indian Ocean
  MU: ["Agalega","Beau Bassin-Rose Hill","Curepipe","Flacq","Grand Port","Moka","Pamplemousses","Plaines Wilhems","Port Louis","Quatre Bornes","Rivière du Rempart","Rivière Noire","Rodrigues","Savanne","Vacoas-Phoenix"],
  SC: ["Anse aux Pins","Anse Boileau","Anse Etoile","Anse Royale","Au Cap","Baie Lazare","Baie Sainte Anne","Beau Vallon","Bel Air","Bel Ombre","Cascade","Glacis","Grand'Anse (Mahé)","Grand'Anse (Praslin)","La Digue","La Rivière Anglaise","Les Mamelles","Mont Buxton","Mont Fleuri","Plaisance","Pointe La Rue","Port Glaud","Roche Caiman","Saint Louis","Takamaka"],
  KM: ["Anjouan","Grande Comore","Mohéli"],
  MV: ["Addu City","Alifu Alifu","Alifu Dhaalu","Baa","Dhaalu","Faafu","Gaafu Alifu","Gaafu Dhaalu","Gnaviyani","Haa Alifu","Haa Dhaalu","Kaafu","Laamu","Lhaviyani","Malé","Meemu","Noonu","Raa","Seenu","Shaviyani","Thaa","Vaavu"],
  // Balkans
  AL: ["Berat","Dibër","Durrës","Elbasan","Fier","Gjirokastër","Korçë","Kukës","Lezhë","Shkodër","Tiranë","Vlorë"],
  BA: ["Brčko District","Federation of Bosnia and Herzegovina","Republika Srpska"],
  XK: ["Đakovica","Gjilan","Kosovska Mitrovica","Peć","Priština","Prizren","Uroševac"],
  MK: ["Aerodrom","Aračinovo","Berovo","Bitola","Bogdanci","Bogovinje","Bosilovo","Brvenica","Butel","Čair","Čaška","Centar","Centar Župa","Češinovo-Obleševo","Čučer-Sandevo","Debar","Debarca","Delčevo","Demir Hisar","Demir Kapija","Dojran","Dolneni","Gevgelija","Gostivar","Gradsko","Ilinden","Jegunovce","Karbinci","Karpoš","Kavadarci","Kičevo","Kisela Voda","Kočani","Konče","Kratovo","Kriva Palanka","Krivogaštani","Kruševo","Kumanovo","Lipkovo","Lozovo","Makedonska Kamenica","Makedonski Brod","Mavrovo i Rostuše","Mogila","Negotino","Novaci","Novo Selo","Ohrid","Pehčevo","Petrovec","Plasnica","Prilep","Probištip","Radoviš","Rankovce","Resen","Rosoman","Saraj","Štip","Šuto Orizari","Sopište","Staro Nagoričane","Struga","Strumica","Studeničani","Sveti Nikole","Tearce","Tetovo","Valandovo","Vasilevo","Veles","Vevčani","Vinica","Vrapčište","Zajas","Zelenikovo","Želino","Zrnovci"],
  ME: ["Andrijevica","Bar","Berane","Bijelo Polje","Budva","Cetinje","Danilovgrad","Gusinje","Herceg Novi","Kolašin","Kotor","Mojkovac","Nikšić","Petrovac","Plav","Pljevlja","Plužine","Podgorica","Rožaje","Šavnik","Tivat","Tuzi","Ulcinj","Žabljak"],
  RS: ["Belgrade","Bor","Braničevo","Central Banat","Jablanica","Kolubara","Mačva","Moravica","Nišava","North Bačka","North Banat","Pčinja","Pirot","Podunavlje","Pomoravlje","Rasina","Raška","South Bačka","South Banat","Srem","Šumadija","Toplica","Vojvodina","West Bačka","Zaječar","Zlatibor"]
};

function getCountryName(code) {
    for (var i = 0; i < countries.length; i++) {
        if (countries[i][0] === code) return countries[i][1];
    }
    return code;
}

function getStates(code) {
    return states[code] || [];
}

return {
    countries: countries,
    states: states,
    getCountryName: getCountryName,
    getStates: getStates
};

})();
