-- ==================== KOITUS SUPABASE SCHEMA ====================
-- This file is mirrored in supabase/migrations/20260621170000_initial_schema.sql
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

-- 0. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 1. PROFILES (extends auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text,
  email text,
  age integer,
  gender text,
  location text,
  country text,
  state text,
  bio text default 'Just joined Koitus!',
  about_me text,
  looking_for text,
  headline text,
  height numeric,
  body_type text,
  education text,
  occupation text,
  smoking text,
  drinking text,
  interests text[] default '{}',
  avatar text default 'https://i.pravatar.cc/400?u=default',
  account_type text default 'customer',
  profile_type text,
  "type" text,
  main_type text,
  sub_type text,
  sub_types text[] default '{}',
  additional_services text[] default '{}',
  role text default 'user',
  is_admin boolean default false,
  online boolean default false,
  coordinates jsonb default '{"lat": -26.1076, "lng": 28.0567}',
  gallery jsonb default '[]',
  social_links jsonb default '{"instagram":"","twitter":"","website":""}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can view all profiles"
  on public.profiles for select
  using (true);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- 2. FORUM CATEGORIES
create table if not exists public.forum_categories (
  id text primary key,
  name text not null,
  icon text,
  color text default '#6366f1',
  description text,
  "order" integer default 0,
  is_provider boolean default false,
  created_at timestamptz default now()
);

alter table public.forum_categories enable row level security;
create policy "Anyone can read forum categories" on public.forum_categories for select using (true);

-- 3. FORUM POSTS
create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  category text references public.forum_categories(id),
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id),
  votes integer default 0,
  replies integer default 0,
  views integer default 0,
  is_answered boolean default false,
  status text default 'pending',
  post_type text default 'user',
  created_at timestamptz default now()
);

alter table public.forum_posts enable row level security;
create policy "Anyone can read approved posts" on public.forum_posts for select using (status = 'approved' or auth.uid() = author_id);
create policy "Users can create posts" on public.forum_posts for insert with check (auth.role() = 'authenticated');
create policy "Users can update own posts" on public.forum_posts for update using (auth.uid() = author_id);

-- 4. FORUM REPLIES
create table if not exists public.forum_replies (
  id bigint generated by default as identity primary key,
  post_id bigint references public.forum_posts(id) on delete cascade,
  author_id uuid references public.profiles(id),
  content text not null,
  votes integer default 0,
  is_best_answer boolean default false,
  created_at timestamptz default now()
);

alter table public.forum_replies enable row level security;
create policy "Anyone can read replies" on public.forum_replies for select using (true);
create policy "Authenticated can reply" on public.forum_replies for insert with check (auth.role() = 'authenticated');

-- 5. PRODUCTS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null,
  category text,
  image text,
  seller_id uuid references public.profiles(id),
  is_featured boolean default false,
  sold integer default 0,
  rating numeric(2,1) default 0,
  status text default 'active',
  created_at timestamptz default now()
);

alter table public.products enable row level security;
create policy "Anyone can read products" on public.products for select using (status = 'active');
create policy "Sellers can manage own products" on public.products for all using (auth.uid() = seller_id);

-- 6. DIRECTORY LISTINGS
create table if not exists public.directory_listings (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  category text not null,
  location text,
  country text,
  state text,
  city text,
  description text,
  phone text,
  email text,
  website text,
  owner_id uuid references public.profiles(id),
  is_featured boolean default false,
  status text default 'active',
  created_at timestamptz default now()
);

alter table public.directory_listings enable row level security;
create policy "Anyone can read listings" on public.directory_listings for select using (status = 'active');
create policy "Users can create listings" on public.directory_listings for insert with check (auth.role() = 'authenticated');
create policy "Owners can manage listings" on public.directory_listings for all using (auth.uid() = owner_id);

-- 7. EVENTS
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  description text,
  date date,
  time time,
  location text,
  coords jsonb default '{"lat": -26.1076, "lng": 28.0567}',
  image text,
  host_id uuid references public.profiles(id),
  is_past boolean default false,
  is_host boolean default false,
  rsvp_count integer default 0,
  created_at timestamptz default now()
);

alter table public.events enable row level security;
create policy "Anyone can read events" on public.events for select using (true);
create policy "Authenticated can create events" on public.events for insert with check (auth.role() = 'authenticated');
create policy "Hosts can update own events" on public.events for update using (auth.uid() = host_id);
create policy "Hosts can delete own events" on public.events for delete using (auth.uid() = host_id);

-- 8. CONVERSATIONS & MESSAGES
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  participant_ids uuid[] not null,
  last_message text,
  last_message_at timestamptz default now(),
  created_at timestamptz default now()
);

alter table public.conversations enable row level security;
create policy "Participants can read conversations" on public.conversations for select using (auth.uid() = any(participant_ids));
create policy "Authenticated can create conversations" on public.conversations for insert with check (auth.uid() = any(participant_ids));
create policy "Participants can update conversations" on public.conversations for update using (auth.uid() = any(participant_ids));

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade,
  sender_id uuid references public.profiles(id),
  text text,
  message_type text default 'text',
  media_url text,
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;
create policy "Participants can read messages" on public.messages for select using (
  exists (select 1 from public.conversations where id = conversation_id and auth.uid() = any(participant_ids))
);
create policy "Participants can send" on public.messages for insert with check (auth.uid() = sender_id);
create policy "Participants can update read status" on public.messages for update using (
  exists (select 1 from public.conversations where id = conversation_id and auth.uid() = any(participant_ids))
);

-- 9. NOTIFICATIONS
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  type text,
  title text,
  text text,
  icon text,
  is_unread boolean default true,
  created_at timestamptz default now()
);

alter table public.notifications enable row level security;
create policy "Users can read own notifications" on public.notifications for select using (auth.uid() = user_id);
create policy "System can create notifications" on public.notifications for insert with check (auth.role() = 'authenticated');

-- 10. WALLET TRANSACTIONS
create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  type text,
  amount numeric(10,2),
  description text,
  created_at timestamptz default now()
);

alter table public.wallet_transactions enable row level security;
create policy "Users can read own transactions" on public.wallet_transactions for select using (auth.uid() = user_id);
create policy "Users can create own transactions" on public.wallet_transactions for insert with check (auth.uid() = user_id);

-- 11. STREAMS
create table if not exists public.streams (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  streamer_id uuid references public.profiles(id),
  is_live boolean default false,
  viewers integer default 0,
  likes integer default 0,
  created_at timestamptz default now()
);

alter table public.streams enable row level security;
create policy "Anyone can read streams" on public.streams for select using (true);
create policy "Authenticated can create streams" on public.streams for insert with check (auth.uid() = streamer_id);
create policy "Streamers can update own streams" on public.streams for update using (auth.uid() = streamer_id);

-- 12. CONTENT
create table if not exists public.content (
  id bigint generated by default as identity primary key,
  type text,
  media text,
  caption text,
  author_id uuid references public.profiles(id),
  likes integer default 0,
  created_at timestamptz default now()
);

alter table public.content enable row level security;
create policy "Anyone can read content" on public.content for select using (true);
create policy "Authenticated can create content" on public.content for insert with check (auth.uid() = author_id);
create policy "Authors can update own content" on public.content for update using (auth.uid() = author_id);
create policy "Authors can delete own content" on public.content for delete using (auth.uid() = author_id);

-- 13. CLUBS
create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  category text,
  image text,
  member_count integer default 0,
  created_at timestamptz default now()
);

alter table public.clubs enable row level security;
create policy "Anyone can read clubs" on public.clubs for select using (true);
create policy "Authenticated can create clubs" on public.clubs for insert with check (auth.role() = 'authenticated');

-- 14. PERSONALS ADS
create table if not exists public.personals (
  id bigint generated by default as identity primary key,
  type text,
  title text,
  description text,
  location text,
  author_id uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.personals enable row level security;
create policy "Anyone can read personals" on public.personals for select using (true);
create policy "Authenticated can create personals" on public.personals for insert with check (auth.uid() = author_id);
create policy "Authors can update own personals" on public.personals for update using (auth.uid() = author_id);
create policy "Authors can delete own personals" on public.personals for delete using (auth.uid() = author_id);

-- 15. STORIES
create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  media text,
  created_at timestamptz default now()
);

alter table public.stories enable row level security;
create policy "Anyone can read stories" on public.stories for select using (true);
create policy "Authenticated can create stories" on public.stories for insert with check (auth.uid() = user_id);
create policy "Users can delete own stories" on public.stories for delete using (auth.uid() = user_id);

-- INDEXES
create index if not exists idx_forum_posts_status on public.forum_posts(status);
create index if not exists idx_forum_posts_author on public.forum_posts(author_id);
create index if not exists idx_messages_conversation on public.messages(conversation_id);
create index if not exists idx_notifications_user on public.notifications(user_id);
create index if not exists idx_directory_listings_country on public.directory_listings(country);
create index if not exists idx_products_category on public.products(category);

-- STORAGE BUCKETS (for user uploads / Supabase Storage)
-- Run this separately in the SQL Editor AFTER creating the tables above.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('media', 'media', true, 52428800, '{"image/*","video/*","audio/*","application/pdf"}')
on conflict (id) do nothing;

-- Allow public access to media bucket
create policy "Public can view media"
  on storage.objects for select
  using (bucket_id = 'media');

create policy "Authenticated users can upload media"
  on storage.objects for insert
  with check (
    bucket_id = 'media'
    and auth.role() = 'authenticated'
  );

create policy "Users can update own media"
  on storage.objects for update
  using (bucket_id = 'media' and auth.uid() = owner);

create policy "Users can delete own media"
  on storage.objects for delete
  using (bucket_id = 'media' and auth.uid() = owner);

-- Auto-create profile on user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, split_part(new.email, '@', 1));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- SEED DATA: Forum Categories
insert into public.forum_categories (id, name, icon, color, description, "order", is_provider) values
  ('general', 'General Discussion', 'comments', '#6366f1', 'Chat about anything and everything', 1, false),
  ('advice', 'Advice & Tips', 'lightbulb', '#f59e0b', 'Get and give advice on dating and relationships', 2, false),
  ('safety', 'Safety & Support', 'shield-alt', '#22c55e', 'Stay safe and support each other', 3, false),
  ('events', 'Events & Meetups', 'calendar-alt', '#8b5cf6', 'Organize and discover events', 4, false),
  ('feedback', 'Feedback & Suggestions', 'comment-dots', '#ec4899', 'Help us improve Koitus', 5, false),
  ('provider-general', 'Provider Discussions', 'briefcase', '#DC143C', 'For service providers only', 1, true),
  ('provider-tips', 'Business Tips', 'chart-line', '#14b8a6', 'Grow your adult entertainment business', 2, true),
  ('provider-safety', 'Safety Protocols', 'user-shield', '#ef4444', 'Best practices for safety', 3, true)
on conflict (id) do nothing;
